name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gnuplot
      run: sudo apt-get install gnuplot
    - name: make
      run: make
    - name: make check
      run: make check

  benchmark_plot:
    runs-on: ubuntu-latest

    steps:
      - name: make benchmark
        run: make benchmark
      - name: make plots
        run: make plots
      - name: upload benchmark plot
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_plot.png
          path: data/plots/plots.png
