name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gnuplot
      run: sudo apt-get install gnuplot
    - name: make
      run: make
    - name: make check
      run: make check

    - name: make benchmark
      run: make benchmark
    - name: make plots
      run: make plots
    - name: upload benchmark plot
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: ./bin/plots/plots.png
      asset_name: plots.png
      asset_content_type: image/png
